import { useState, useEffect, useMemo } from "react";
import { Bell, Settings, User, AltArrowRight as ChevronRight, Moon, Sun, TrashBinMinimalistic as Trash2, BellBing as BellRing, CheckCircle as Check, ChatLine as MessageSquare, Restart as RefreshIcon, CloseCircle as XIcon, InfoCircle, Danger as ErrorIcon, DangerCircle as WarningIcon, AltArrowDown as ChevronDown, AltArrowUp as ChevronUp } from "@solar-icons/react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { formatDistanceToNow } from "date-fns";
import { es } from "date-fns/locale";
import { Button } from "@/components/ui/button";
import { notify } from "@/lib/notifications";
import { notificationService as pushNotificationService } from "@/services/PushNotificationService";
import { useNotifications } from "@/contexts/NotificationContext";
import { notificationService } from "@/services/notifications.service";
import { supabase } from "@/integrations/supabase/client";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

import { useUser } from "@/contexts/UserContext";

const DUMMY_SETTINGS: Array<{ id: string; title: string; value: string }> = [];

// --- Tab types for the notification panel ---
type NotifTab = 'todas' | 'mencionado' | 'sistema';

// System categories (notifications generated by the system, not user announcements)
const SYSTEM_CATEGORIES = ['SYSTEM', 'ALERTA', 'INVENTARIO', 'VENCIMIENTO'];
// "Mencionado" = announcements sent by admin to the branch, and the admin's own sent log
const MENTIONED_CATEGORIES = ['ANUNCIO', 'ENVIADO'];

// Icon for notification type
function NotifTypeIcon({ type, className }: { type: string; className?: string }) {
  const baseClass = cn("w-5 h-5 shrink-0", className);
  switch (type) {
    case 'error':
      return <ErrorIcon className={cn(baseClass, "text-red-500")} />;
    case 'warning':
      return <WarningIcon className={cn(baseClass, "text-amber-500")} />;
    case 'success':
      return <Check className={cn(baseClass, "text-emerald-500")} />;
    default:
      return <InfoCircle className={cn(baseClass, "text-blue-500")} />;
  }
}

// Relative time helper
function timeAgo(dateStr: string) {
  try {
    return formatDistanceToNow(new Date(dateStr), { addSuffix: false, locale: es });
  } catch {
    return '';
  }
}

export function MessagesMenu() {
  const [open, setOpen] = useState(false);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <div className="inline-block relative">
        <button onClick={() => setOpen(true)} aria-label="Mensajes" className="inline-flex h-10 w-10 items-center justify-center rounded-full hover:bg-black/5 dark:hover:bg-white/10 transition-colors focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2">
          <MessageSquare className="w-4 h-4 text-muted-foreground" />
        </button>
      </div>
      <DialogContent className="w-[420px] p-0">
        <DialogHeader className="p-4 border-b">
          <DialogTitle>Mensajes</DialogTitle>
        </DialogHeader>
        <div className="p-8 text-center">
          <MessageSquare className="w-12 h-12 text-muted/20 mx-auto mb-4" />
          <p className="text-muted-foreground">No tienes mensajes nuevos en este momento.</p>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export function NotificationsMenu() {
  const [open, setOpen] = useState(false);
  const { notifications, unreadCount, markAsRead, markAllAsRead, deleteNotification } = useNotifications();
  const { user } = useUser();
  const [activeTab, setActiveTab] = useState<NotifTab>('todas');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Admin Announcement State
  const [showAnnouncementDialog, setShowAnnouncementDialog] = useState(false);
  const [branches, setBranches] = useState<string[]>([]);
  const [selectedBranch, setSelectedBranch] = useState("");
  const [announcementMessage, setAnnouncementMessage] = useState("");
  const [isSending, setIsSending] = useState(false);

  useEffect(() => {
    if (user?.username === 'gcoz') {
      loadBranches();
    }
  }, [user]);

  const loadBranches = async () => {
    const { data } = await supabase.from('branches').select('name').order('name');
    if (data) setBranches(data.map(b => b.name));
  };

  // Filtered notifications by tab
  const filteredNotifications = useMemo(() => {
    if (activeTab === 'sistema') {
      return notifications.filter(n => SYSTEM_CATEGORIES.includes((n.category || '').toUpperCase()));
    }
    if (activeTab === 'mencionado') {
      return notifications.filter(n => MENTIONED_CATEGORIES.includes((n.category || '').toUpperCase()));
    }
    return notifications; // 'todas'
  }, [notifications, activeTab]);

  // Counts for tabs
  const counts = useMemo(() => ({
    todas: notifications.length,
    mencionado: notifications.filter(n => MENTIONED_CATEGORIES.includes((n.category || '').toUpperCase())).length,
    sistema: notifications.filter(n => SYSTEM_CATEGORIES.includes((n.category || '').toUpperCase())).length,
  }), [notifications]);

  const handleSendAnnouncement = async () => {
    if (!selectedBranch || !announcementMessage.trim()) {
      notify.error("Error", "Debes elegir una sucursal y escribir un mensaje");
      return;
    }

    setIsSending(true);
    try {
      await notificationService.sendToBranch(selectedBranch, {
        title: "📣 Anuncio de Administración",
        message: announcementMessage,
        type: 'warning'
      }, user?.id);
      notify.success("Enviado", `Anuncio enviado a ${selectedBranch}`);
      setShowAnnouncementDialog(false);
      setAnnouncementMessage("");
    } catch (e) {
      notify.error("Error", "No se pudo enviar el anuncio");
    } finally {
      setIsSending(false);
    }
  };

  const handleMarkAllRead = async () => {
    await markAllAsRead();
    notify.success("Listo", "Todas las notificaciones marcadas como leídas");
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    // Quick visual feedback
    setTimeout(() => setIsRefreshing(false), 800);
  };

  const tabs: { key: NotifTab; label: string }[] = [
    { key: 'todas', label: 'Todas' },
    { key: 'mencionado', label: 'Mencionado' },
    { key: 'sistema', label: 'Sistema' },
  ];

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <div className="inline-block relative">
        <button
          onClick={() => setOpen(true)}
          aria-label="Notificaciones"
          className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-muted/50 border border-border/40 hover:bg-muted/80 dark:hover:bg-white/10 transition-colors focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        >
          <Bell className={`w-4 h-4 ${unreadCount > 0 ? 'text-accent' : 'text-muted-foreground'}`} />
          {unreadCount > 0 && (
            <span
              className="absolute -top-1 -right-1 min-w-[16px] h-4 px-1 rounded-full bg-accent text-white text-[10px] font-bold flex items-center justify-center ring-2 ring-background shadow-sm"
              role="status"
              aria-label={`${unreadCount} notificaciones nuevas`}
            >
              {unreadCount}
            </span>
          )}
        </button>
      </div>

      <DialogContent className="w-[400px] p-0 gap-0 rounded-2xl overflow-hidden border border-border/60 shadow-2xl">
        {/* ── Header ── */}
        <div className="flex items-center justify-between px-5 pt-5 pb-3 pr-12">
          <DialogTitle className="text-base font-semibold tracking-tight">Notificaciones</DialogTitle>
          <div className="flex items-center gap-1">
            <button
              className={cn("p-1.5 rounded-lg hover:bg-muted/80 transition-all text-muted-foreground", isRefreshing && "animate-spin")}
              onClick={handleRefresh}
              title="Actualizar"
            >
              <RefreshIcon className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* ── Tabs ── */}
        <div className="flex items-center gap-1 px-5 pb-3">
          {tabs.map(tab => {
            const isActive = activeTab === tab.key;
            const count = counts[tab.key];
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={cn(
                  "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all border",
                  isActive
                    ? "bg-foreground text-background border-foreground shadow-sm"
                    : "bg-transparent text-muted-foreground border-border/60 hover:bg-muted/60 hover:text-foreground"
                )}
              >
                {tab.label}
                <span className={cn(
                  "text-[10px] font-bold tabular-nums min-w-[16px] text-center",
                  isActive ? "text-background/70" : "text-muted-foreground/60"
                )}>
                  {count}
                </span>
              </button>
            );
          })}
        </div>

        {/* ── Divider ── */}
        <div className="h-px bg-border/40" />

        {/* ── Notification List ── */}
        {filteredNotifications.length > 0 ? (
          <div className="max-h-[420px] overflow-y-auto overscroll-contain">
            {filteredNotifications.map((n, idx) => {
              const isExpanded = expandedId === n.id;
              return (
                <div
                  key={n.id}
                  className={cn(
                    "group flex items-start gap-3 px-5 py-3.5 transition-colors border-b border-border/20 last:border-b-0",
                    !n.is_read
                      ? "bg-accent/[0.04] hover:bg-accent/[0.08]"
                      : "hover:bg-muted/40"
                  )}
                  onClick={() => {
                    if (!n.is_read) markAsRead(n.id);
                  }}
                >
                  {/* Icon */}
                  <div className="mt-0.5">
                    <NotifTypeIcon type={n.type || 'info'} />
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-2">
                      <p className={cn(
                        "text-[13px] leading-snug",
                        !n.is_read ? "font-semibold text-foreground" : "font-medium text-foreground/80"
                      )}>
                        {n.title}
                      </p>
                      {/* Action buttons */}
                      <div className="flex items-center gap-0 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                        {n.message && (
                          <button
                            onClick={(e) => { e.stopPropagation(); setExpandedId(isExpanded ? null : n.id); }}
                            className="p-1 rounded-md hover:bg-muted/80 text-muted-foreground transition-colors"
                            title={isExpanded ? "Contraer" : "Expandir"}
                          >
                            {isExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                          </button>
                        )}
                        <button
                          onClick={(e) => { e.stopPropagation(); if (!n.is_read) markAsRead(n.id); }}
                          className="p-1 rounded-md hover:bg-muted/80 text-muted-foreground transition-colors"
                          title="Marcar como leída"
                        >
                          <XIcon className="w-3.5 h-3.5" />
                        </button>
                        {MENTIONED_CATEGORIES.includes((n.category || '').toUpperCase()) && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              if (confirm("¿Estás seguro de que deseas eliminar esta notificación?")) {
                                deleteNotification(n.id);
                              }
                            }}
                            className="p-1 rounded-md hover:bg-destructive/10 text-destructive/70 hover:text-destructive transition-colors ml-0.5"
                            title="Eliminar notificación"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        )}
                      </div>
                    </div>

                    {/* Expandable message */}
                    {isExpanded && n.message && (
                      <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed pr-4">
                        {n.message}
                      </p>
                    )}

                    {/* Preview message when collapsed */}
                    {!isExpanded && n.message && (
                      <p className="text-xs text-muted-foreground mt-0.5 line-clamp-1">
                        {n.message}
                      </p>
                    )}

                    {/* Timestamp */}
                    <p className="text-[11px] text-muted-foreground/60 mt-1.5">
                      {timeAgo(n.created_at)}
                    </p>
                  </div>

                  {/* Unread dot */}
                  {!n.is_read && (
                    <div className="mt-2 shrink-0">
                      <div className="h-2 w-2 rounded-full bg-accent" />
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        ) : (
          <div className="py-12 px-5 text-center">
            <Bell className="w-10 h-10 text-muted-foreground/20 mx-auto mb-3" />
            <p className="text-sm text-muted-foreground">No hay notificaciones</p>
            <p className="text-xs text-muted-foreground/60 mt-1">Las nuevas aparecerán aquí</p>
          </div>
        )}

        {/* ── Footer ── */}
        <div className="h-px bg-border/40" />
        <div className="flex items-center justify-between px-5 py-3">
          <button
            onClick={handleMarkAllRead}
            disabled={unreadCount === 0}
            className={cn(
              "text-xs font-medium transition-colors",
              unreadCount > 0 ? "text-foreground hover:text-accent cursor-pointer" : "text-muted-foreground/40 cursor-default"
            )}
          >
            Marcar todas como leídas
          </button>
          {user?.username === 'gcoz' && (
            <button
              onClick={() => {
                setOpen(false);
                setShowAnnouncementDialog(true);
              }}
              className="text-xs font-medium text-muted-foreground hover:text-accent transition-colors cursor-pointer"
            >
              Enviar anuncio
            </button>
          )}
        </div>
      </DialogContent>

      {/* Admin Announcement Dialog */}
      <Dialog open={showAnnouncementDialog} onOpenChange={setShowAnnouncementDialog}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <BellRing className="w-5 h-5 text-accent" />
              Enviar Anuncio a Sucursal
            </DialogTitle>
            <DialogDescription>
              Este mensaje llegará a todas las personas de la sucursal seleccionada.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="branch">Sucursal Destino</Label>
              <Select value={selectedBranch} onValueChange={setSelectedBranch}>
                <SelectTrigger id="branch">
                  <SelectValue placeholder="Seleccionar sucursal..." />
                </SelectTrigger>
                <SelectContent>
                  {branches.map((b) => (
                    <SelectItem key={b} value={b}>{b}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="message">Mensaje</Label>
              <Textarea
                id="message"
                placeholder="Escribe el aviso aquí..."
                className="min-h-[100px]"
                value={announcementMessage}
                onChange={(e) => setAnnouncementMessage(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="ghost" onClick={() => setShowAnnouncementDialog(false)}>
              Cancelar
            </Button>
            <Button
              className="bg-accent hover:bg-accent/90"
              onClick={handleSendAnnouncement}
              disabled={isSending || !selectedBranch || !announcementMessage}
            >
              {isSending ? "Enviando..." : "Enviar Ahora"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Dialog>
  );
}

export function SettingsMenu() {
  const [open, setOpen] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    const savedTheme = localStorage.getItem("theme");
    const isDark = savedTheme === "dark" || document.documentElement.classList.contains("dark");
    setIsDarkMode(isDark);
  }, []);

  const handleToggleDarkMode = () => {
    const html = document.documentElement;
    if (html.classList.contains("dark")) {
      html.classList.remove("dark");
      localStorage.setItem("theme", "light");
      setIsDarkMode(false);
    } else {
      html.classList.add("dark");
      localStorage.setItem("theme", "dark");
      setIsDarkMode(true);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <div className="inline-block">
        <button
          onClick={() => setOpen(true)}
          aria-label="Configuración"
          className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-muted/50 border border-border/40 hover:bg-muted/80 dark:hover:bg-white/10 transition-colors focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        >
          <Settings className="w-4 h-4 text-muted-foreground" />
        </button>
      </div>
      <DialogContent className="w-[420px] p-0">
        <DialogHeader className="p-4 border-b">
          <DialogTitle>Configuración</DialogTitle>
        </DialogHeader>
        <div className="p-4">
          <ul className="divide-y">
            <li className="py-3 flex items-center justify-between">
              <div>
                <div className="font-medium">Tema</div>
                <div className="text-xs text-muted-foreground">{isDarkMode ? "Oscuro" : "Claro"}</div>
              </div>
              <button
                onClick={handleToggleDarkMode}
                className="inline-flex items-center justify-center p-2 rounded-lg bg-muted hover:bg-accent/30 transition-colors"
                aria-label="Cambiar tema"
              >
                {isDarkMode ? (
                  <Moon className="w-4 h-4 text-muted-foreground" />
                ) : (
                  <Sun className="w-4 h-4 text-muted-foreground" />
                )}
              </button>
            </li>
          </ul>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export function UserMenu() {
  const [open, setOpen] = useState(false);
  const { user, logout } = useUser();

  const getInitials = () => {
    if (!user) return "??";

    // Si es una sucursal, usar F + Inicial de la sucursal
    if (user.role === 'branch' && user.branchName) {
      const branchName = user.branchName.replace(/^farmacia\s+/i, '');
      return `F${branchName.charAt(0).toUpperCase()}`;
    }

    // Si es un admin/mod, usar iniciales del nombre
    const names = user.name.split(' ');
    if (names.length >= 2) {
      return (names[0].charAt(0) + names[names.length - 1].charAt(0)).toUpperCase();
    }
    return user.name.charAt(0).toUpperCase();
  };

  const initials = getInitials();

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <div className="inline-block">
        <button
          onClick={() => setOpen(true)}
          aria-label="Usuario"
          className="group flex items-center justify-center h-10 w-10 rounded-xl overflow-hidden hover:ring-2 hover:ring-foreground/10 transition-all bg-muted/50 border border-border/40"
        >
          <div className="h-full w-full flex items-center justify-center text-[11px] font-bold text-foreground transition-colors group-hover:bg-foreground group-hover:text-background border-none">
            {initials}
          </div>
        </button>
      </div>
      <DialogContent className="w-[360px] p-0">
        <DialogHeader className="p-4 border-b">
          <DialogTitle>Cuenta</DialogTitle>
        </DialogHeader>
        <div className="p-4">
          <div className="flex items-center gap-3">
            <div className="rounded-full bg-primary/10 w-12 h-12 flex items-center justify-center font-bold text-primary">
              {initials}
            </div>
            <div>
              <div className="font-medium">{user?.name}</div>
              <div className="text-xs text-muted-foreground">{user?.username || user?.role}</div>
            </div>
          </div>
          <div className="mt-4 divide-y">
            <div className="py-3">
              <button
                onClick={() => setOpen(false)}
                className="w-full text-left hover:text-primary transition-colors font-medium"
              >
                Ver perfil
              </button>
            </div>
            <div className="py-3">
              <button
                onClick={() => {
                  setOpen(false);
                  logout();
                }}
                className="w-full text-left hover:text-destructive transition-colors font-medium"
              >
                Cerrar sesión
              </button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
